#!/usr/bin/env python3
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Aggregate runner outputs into a cross-implementation STATUS.md matrix.

Reads a directory of runner-output files named <implementation>.txt (each the
captured stdout of a conformance runner) and writes a Markdown status matrix.
It reports counts and divergences; it does not block.

Usage:
  dev/build-status-matrix.py <outputs-dir> [<status.md>]     render the matrix
  dev/build-status-matrix.py --json <outputs-dir> <json-dir> per-impl badge JSON
"""

import glob
import json
import os
import re
import sys

TOTALS_RE = re.compile(
    r"TOTALS:\s*(\d+)\s*cases\s*\|\s*PASS=(\d+)\s*FAIL=(\d+)\s*UNSUPPORTED=(\d+)\s*SKIP=(\d+)"
)

HEADER = """<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~   http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->

# Type-surface conformance status

Generated by `dev/build-status-matrix.py` from the type-surface runners
(`table-spec/types/`). It reports; it does not block:

- **PASS** - matches the spec-derived fixture.
- **FAIL** - a genuine divergence from the spec-derived fixture.
- **UNSUPPORTED** - a type the implementation has not built yet (a skip-list candidate).
"""


def parse(path):
    fails = unsup = ""
    totals = None
    with open(path, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            m = TOTALS_RE.search(line)
            if m:
                totals = tuple(int(x) for x in m.groups())  # cases,pass,fail,unsup,skip
            elif line.startswith("FAIL ids:"):
                fails = line.split(":", 1)[1].strip()
            elif line.startswith("UNSUPPORTED ids:"):
                unsup = line.split(":", 1)[1].strip()
    return totals, fails, unsup


def badge_fields(totals):
    """(message, color) for a shields.io endpoint badge from a parsed TOTALS tuple.

    Four distinct states so a crash is never a false green: green all-pass,
    yellow unsupported-only, red any FAIL, lightgrey no report (runner errored).
    """
    if totals is None:
        return "no report", "lightgrey"
    cases, p, f, u, _s = totals
    message = f"{p}/{cases} passed"
    if f > 0:
        return message, "red"
    if u > 0:
        return message, "yellow"
    return message, "brightgreen"


def write_badges(outdir, jsondir):
    os.makedirs(jsondir, exist_ok=True)
    n = 0
    for path in sorted(glob.glob(os.path.join(outdir, "*.txt"))):
        impl = os.path.splitext(os.path.basename(path))[0]
        totals, _fails, _unsup = parse(path)
        message, color = badge_fields(totals)
        blob = {"schemaVersion": 1, "label": impl, "message": message, "color": color}
        with open(os.path.join(jsondir, impl + ".json"), "w", encoding="utf-8") as fh:
            json.dump(blob, fh)
        n += 1
    print(f"wrote {n} badge json file(s) to {jsondir}")
    return 0


def main():
    if len(sys.argv) >= 2 and sys.argv[1] == "--json":
        if len(sys.argv) < 4:
            print("usage: build-status-matrix.py --json <outputs-dir> <json-dir>", file=sys.stderr)
            return 2
        return write_badges(sys.argv[2], sys.argv[3])
    if len(sys.argv) < 2:
        print("usage: build-status-matrix.py <outputs-dir> [<status.md>]", file=sys.stderr)
        return 2
    outdir = sys.argv[1]
    dest = sys.argv[2] if len(sys.argv) > 2 else None

    rows = []
    divergences = []
    for path in sorted(glob.glob(os.path.join(outdir, "*.txt"))):
        impl = os.path.splitext(os.path.basename(path))[0]
        totals, fails, unsup = parse(path)
        if totals is None:
            rows.append((impl, "-", "-", "-", "-", "no TOTALS line found"))
            continue
        cases, p, f, u, s = totals
        if f > 0:
            note = f"{f} divergence(s)"
        elif u > 0:
            note = f"conformant; {u} unsupported"
        else:
            note = "conformant"
        rows.append((impl, p, f, u, s, note))
        if fails:
            divergences.append(f"- **{impl}** FAIL: {fails}")
        if unsup:
            divergences.append(f"- **{impl}** UNSUPPORTED: {unsup}")

    lines = [HEADER, "", "| Implementation | Pass | Fail | Unsupported | Skip | Status |",
             "|---|---|---|---|---|---|"]
    for impl, p, f, u, s, note in rows:
        lines.append(f"| {impl} | {p} | {f} | {u} | {s} | {note} |")
    lines.append("")
    lines.append("## Divergences and gaps")
    lines.append("")
    lines.extend(divergences or ["None reported."])
    lines.append("")
    text = "\n".join(lines) + "\n"

    if dest:
        with open(dest, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"wrote {dest} ({len(rows)} implementations)")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
